{
 "title": "External Secrets Operator - Custom",
 "time": { "from": "now-6h", "to": "now" },
 "templating": {
  "list": [
   { "name": "datasource", "query": "prometheus" },
   {
    "name": "cluster",
    "label": "cluster",
    "query": {
     "query": "label_values(controller_runtime_active_workers{}, cluster)"
    }
   },
   {
    "name": "controller",
    "label": "controller",
    "query": {
     "query": "label_values(controller_runtime_active_workers{cluster=\"$cluster\",service=~\".*external-secrets.*\"}, controller)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "Total Sync Call",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "sum by(name) (rate(externalsecret_sync_calls_total{cluster=\"${cluster}\"}[$__rate_interval]))",
     "legendFormat": "{{name}}"
    }
   ]
  },
  {
   "title": "Total Sync Calls Error",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "targets": [
    {
     "expr": "sum by(name) (rate(externalsecret_sync_calls_error{cluster=\"${cluster}\"}[$__rate_interval]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Work Queue ",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 8 },
   "targets": [
    {
     "expr": "sum(workqueue_depth{cluster=\"${cluster}\"}) by (name)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Active Workers by Controller",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 8 },
   "targets": [
    {
     "expr": "sum(controller_runtime_active_workers{controller=~\"$controller\", cluster=\"${cluster}\"}) by (controller)",
     "legendFormat": "{{controller}}"
    }
   ]
  },
  {
   "title": "Reconcile Latency: $controller",
   "type": "heatmap",
   "gridPos": { "h": 8, "w": 4.8, "x": 0, "y": 18 },
   "repeat": "controller",
   "targets": [
    {
     "expr": "rate(controller_runtime_reconcile_time_seconds_bucket{cluster=\"${cluster}\",service=~\".*external-secrets.*\",controller=~\"$controller\"}[$__rate_interval])",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}