{
 "title": "Harbor Custom",
 "time": { "from": "now-6h", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "cluster",
    "label": "cluster",
    "query": {
     "query": "label_values(harbor_health{}, cluster)"
    }
   },
   {
    "name": "job",
    "label": "job",
    "query": {
     "query": "label_values(harbor_health{cluster=\"$cluster\"}, job)"
    }
   },
   {
    "name": "namespace",
    "label": "namespace",
    "query": {
     "query": "label_values(harbor_health{cluster=\"$cluster\",job=\"$job\"}, namespace)"
    }
   },
   {
    "name": "instance",
    "label": "instance",
    "query": {
     "query": "label_values(harbor_health{cluster=\"$cluster\",job=\"$job\"}, instance)"
    }
   },
   {
    "name": "service",
    "label": "service",
    "query": {
     "query": "label_values(process_cpu_seconds_total{cluster=\"$cluster\",}, service)"
    }
   }
  ]
 },
 "panels": [
  { "title": "Harbor Status", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Running Time",
   "type": "stat",
   "gridPos": { "h": 4, "w": 6, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "time() - process_start_time_seconds{job=\"$job\", instance=\"$instance\"}"
    }
   ]
  },
  {
   "title": "Harbor Health",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 6, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "harbor_health{job=\"$job\", instance=\"$instance\"}"
    }
   ]
  },
  {
   "title": "Core Status",
   "type": "stat",
   "gridPos": { "h": 2, "w": 3, "x": 9, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "harbor_up{job=\"$job\", instance=\"$instance\", component=\"core\"}"
    }
   ]
  },
  {
   "title": "Registry Status",
   "type": "stat",
   "gridPos": { "h": 2, "w": 3, "x": 12, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "harbor_up{job=\"$job\", instance=\"$instance\", component=\"registry\"}"
    }
   ]
  },
  {
   "title": "Database Status",
   "type": "stat",
   "gridPos": { "h": 2, "w": 3, "x": 15, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "harbor_up{job=\"$job\", instance=\"$instance\", component=\"database\"}"
    }
   ]
  },
  {
   "title": "Jobservice Status",
   "type": "stat",
   "gridPos": { "h": 2, "w": 3, "x": 18, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "harbor_up{job=\"$job\", instance=\"$instance\", component=\"jobservice\"}"
    }
   ]
  },
  {
   "title": "Portal Status",
   "type": "stat",
   "gridPos": { "h": 2, "w": 3, "x": 9, "y": 3 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "harbor_up{job=\"$job\", instance=\"$instance\", component=\"portal\"}"
    }
   ]
  },
  {
   "title": "Registryctl Status",
   "type": "stat",
   "gridPos": { "h": 2, "w": 3, "x": 12, "y": 3 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "harbor_up{job=\"$job\", instance=\"$instance\", component=\"registryctl\"}"
    }
   ]
  },
  {
   "title": "Redis Status",
   "type": "stat",
   "gridPos": { "h": 2, "w": 3, "x": 15, "y": 3 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "harbor_up{job=\"$job\", instance=\"$instance\", component=\"redis\"}"
    }
   ]
  },
  {
   "title": "Trivy Status",
   "type": "stat",
   "gridPos": { "h": 2, "w": 3, "x": 18, "y": 3 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "harbor_up{job=\"$job\", instance=\"$instance\", component=\"trivy\"}"
    }
   ]
  },
  { "title": "CPU", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 5 } },
  {
   "title": "CPU by Service Pod",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 6 },
   "targets": [
    {
     "expr": "sum by(pod) (rate(process_cpu_seconds_total{cluster=\"${cluster}\",service=\"${service}\"}[1m]))",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  {
   "title": "CPU by Service",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 6 },
   "targets": [
    {
     "expr": "sum by(service) (rate(process_cpu_seconds_total{cluster=\"${cluster}\",service=\"${service}\"}[1m]))",
     "legendFormat": "{{service}}"
    }
   ]
  },
  {
   "title": "CPU by Namespace",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 15 },
   "targets": [
    {
     "expr": "sum(\n  node_namespace_pod_container:container_cpu_usage_seconds_total:sum_irate{cluster=\"$cluster\", namespace=\"$namespace\"}\n* on(namespace,pod)\n  group_left(workload) namespace_workload_pod:kube_pod_owner:relabel{cluster=\"$cluster\", namespace=\"$namespace\"}\n) by (workload)",
     "legendFormat": "{{workload}}"
    }
   ]
  },
  { "title": "Memory", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 24 } },
  {
   "title": "Memory by Namespace",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 25 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "process_resident_memory_bytes{job=\"$job\", instance=\"$instance\"} + process_virtual_memory_bytes{job=\"$job\", instance=\"$instance\"}",
     "legendFormat": "{{namespace}}"
    }
   ]
  },
  {
   "title": "Memory by Service",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 25 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "process_resident_memory_bytes{service=\"${service}\"} + process_virtual_memory_bytes{service=\"${service}\"}",
     "legendFormat": "{{pod}}"
    }
   ]
  }
 ]
}