apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: consul
  namespace: argocd
  labels:
    name: database
spec:
  project: gitops
  source:
    repoURL: https://github.com/tankibaj/gitops-scratch-paper.git
    targetRevision: development
    path: consul
    helm:
      releaseName: consul
  destination:
    server: https://kubernetes.default.svc
    namespace: consul
  syncPolicy:
    syncOptions:
      - CreateNamespace=true