---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: guestbook-appset
  namespace: argocd
  labels:
    name: demo
spec:
  project: gitops
  source:
    repoURL: https://github.com/tankibaj/gitops-scratch-paper.git
    targetRevision: development
    path: demo-progressive-rollout
  destination:
    server: https://kubernetes.default.svc
    namespace: argocd
#  syncPolicy:
#    automated: { }