apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: harbor
  namespace: argocd
  labels:
    name: harbor
spec:
  project: gitops
  source:
    repoURL: https://github.com/tankibaj/gitops-scratch-paper.git
    path: harbor-high-availability
    targetRevision: main
    helm:
      releaseName: harbor
      valueFiles:
        - values.yaml
        - secrets.enc.yaml
  destination:
    server: https://kubernetes.default.svc
    namespace: harbor
#  syncPolicy:
#    automated: { }