apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: loki
  namespace: argocd
  labels:
    name: logging
spec:
  project: gitops
  source:
    repoURL: https://github.com/tankibaj/gitops-scratch-paper.git
    targetRevision: main
    path: loki-distributed
    helm:
      releaseName: loki
  destination:
    server: https://kubernetes.default.svc
    namespace: loki
  syncPolicy:
    syncOptions:
      - CreateNamespace=true