apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: vault
  namespace: argocd
  labels:
    name: secrets
spec:
  project: gitops
  sources:
    - repoURL: https://helm.releases.hashicorp.com
      chart: vault
      targetRevision: v0.23.0
      helm:
        version: v3
        releaseName: vault
        valueFiles:
          - $values/vault/values.yaml
#          - $values/vault/secrets.enc.yaml
    - ref: values
      repoURL: https://github.com/tankibaj/gitops-scratch-paper.git
      targetRevision: development
  destination:
    server: https://kubernetes.default.svc
    namespace: vault
  syncPolicy:
    syncOptions:
      - CreateNamespace=true
  ignoreDifferences:
    - group: admissionregistration.k8s.io
      kind: MutatingWebhookConfiguration
      jsonPointers:
        - /webhooks