apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: velero
  namespace: argocd
  labels:
    name: velero
spec:
  project: gitops
  source:
    repoURL: https://github.com/tankibaj/gitops-scratch-paper.git
    targetRevision: development
    path: velero
  destination:
    server: https://kubernetes.default.svc
    namespace: argocd
  syncPolicy:
    automated: { }