apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: argo-workflows
  namespace: argocd
  labels:
    name: workflows
spec:
  project: gitops
  sources:
    - repoURL: https://argoproj.github.io/argo-helm
      chart: argo-workflows
      targetRevision: 0.22.8
      helm:
        version: v3
        releaseName: argo-workflows
        valueFiles:
          - $values/components/argo-workflows/values.yaml
    - ref: values
      repoURL: https://github.com/tankibaj/gitops-scratch-paper.git
      targetRevision: development
  destination:
    server: https://kubernetes.default.svc
    namespace: argo
#  syncPolicy:
#    automated: { }