apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: argo-events
  namespace: argocd
  labels:
    name: argo-events
spec:
  project: gitops
  sources:
    - repoURL: https://argoproj.github.io/argo-helm
      chart: argo-events
      targetRevision: 2.4.2
      helm:
        version: v3
        releaseName: argo-events
        valueFiles:
          - $values/components/argo-events/values.yaml
    - ref: values
      repoURL: https://github.com/tankibaj/gitops-scratch-paper.git
      targetRevision: main
  destination:
    server: https://kubernetes.default.svc
    namespace: argo-events
  syncPolicy:
    syncOptions:
      - CreateNamespace=true
#    automated: { }