apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: cortex
  namespace: argocd
  labels:
    name: observability
spec:
  project: gitops
  source:
    repoURL: https://github.com/tankibaj/gitops-scratch-paper.git
    targetRevision: development
    path: components/cortex/aws
    helm:
      releaseName: cortex
  destination:
    server: https://kubernetes.default.svc
    namespace: cortex
  syncPolicy:
    syncOptions:
      - CreateNamespace=true