apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: gitea
  namespace: argocd
  labels:
    name: scm
spec:
  project: gitops
  sources:
    - repoURL: https://dl.gitea.io/charts
      chart: gitea
      targetRevision: 10.1.4
      helm:
        version: v3
        releaseName: gitea
        valueFiles:
          - $values/components/gitea/values.yaml
          - $values/components/gitea/secrets.enc.yaml
    - ref: values
      repoURL: https://github.com/tankibaj/gitops-scratch-paper.git
      targetRevision: main
  destination:
    server: https://kubernetes.default.svc
    namespace: gitea
  syncPolicy:
    syncOptions:
      - CreateNamespace=true