apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: harbor
  namespace: argocd
  labels:
    name: harbor
spec:
  project: gitops
  source:
    repoURL: https://github.com/tankibaj/gitops-scratch-paper.git
    path: components/harbor/harbor-high-availability
    targetRevision: main
    helm:
      releaseName: harbor
      valueFiles:
        - values.yaml
        - secrets.enc.yaml
  destination:
    server: https://kubernetes.default.svc
    namespace: harbor
  syncPolicy:
    automated: { }
  ignoreDifferences:
    - group: "*"
      kind: Secret
      jsonPointers:
        - /data/tls.crt
        - /data/tls.key
        - /data/REGISTRY_HTPASSWD
        - /data/CSRF_KEY
        - /data/secret
        - /data/JOBSERVICE_SECRET
        - /data/REGISTRY_HTTP_SECRET
        - /spec/template/metadata/annotations/checksum/secret
        - /spec/template/metadata/annotations/checksum/secret-jobservice
        - /spec/template/metadata/annotations/checksum/secret-core
    - group: apps
      kind: Deployment
      jsonPointers:
        - /spec/template/metadata/annotations