apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: nginx-public
  namespace: argocd
  labels:
    name: ingress-controller
spec:
  project: gitops
  sources:
    - repoURL: https://kubernetes.github.io/ingress-nginx
      chart: ingress-nginx
      targetRevision: 4.7.1 #4.2.4
      helm:
        version: v3
        releaseName: nginx
        valueFiles:
          - $values/components/nginx/baremetal-values.yaml
#          - $values/components/nginx/eks_values_chart_v4.2.4.yaml
#          - $values/components/nginx/eks_values_chart_v4.7.1.yaml
    - ref: values
      repoURL: https://github.com/tankibaj/gitops-scratch-paper.git
      targetRevision: development
  destination:
    server: https://kubernetes.default.svc
    namespace: nginx-public
  syncPolicy:
    syncOptions:
      - CreateNamespace=true