apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: plugin-demo
  namespace: argocd
spec:
  destination:
    server: https://kubernetes.default.svc
    namespace: default
  project: default
  source:
    path: kubernetes/argocd/manifests/plugin-example
    plugin:
      env:
        - name: FOO
          value: bar
    repoURL: https://github.com/thedatabaseme/cookbooks.git
    targetRevision: HEAD
  syncPolicy:
    automated:
      prune: true
      selfHeal: true