apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: pr-appset
spec:
  generators:
    - pullRequest:
        gitea:
          owner: myorg
          repo: myrepository
          api: https://gitea.mydomain.com/
          tokenRef:
            secretName: gitea-token
            key: token
          insecure: true  # Use this only if you are sure about the security implications
        requeueAfterSeconds: 1800  # Polling interval for changes in pull requests
        # Include any pull request ending with "argocd". (optional)
        filters:
          - branchMatch: ".*-argocd"  # Only consider PRs whose source branches end with '-argocd'
  template:
    metadata:
      name: 'myapp-{{branch}}-{{number}}'  # Dynamic application name
    spec:
      project: default
      source:
        repoURL: 'https://gitea.mydomain.com/myorg/myrepository.git'
        targetRevision: '{{head_sha}}'  # Use the head SHA of the pull request
#        kustomize:
#          nameSuffix: '-{{branch}}'
#          commonLabels:
#            app.kubernetes.io/instance: '{{branch}}-{{number}}'
#          images:
#            - ghcr.io/myorg/myrepo:{{head_sha}}
        helm:
          parameters:
            - name: "image.tag"
              value: "pull-{{head_sha}}"
      destination:
        server: https://kubernetes.default.svc
        namespace: 'pr-{{number}}'  # Dynamic namespace based on PR number