harbor:
  expose:
    type: ingress
    tls:
      enabled: false
    ingress:
      hosts:
        core: registry.local.naim.run
      className: nginx-public
  
  externalURL: https://registry.local.naim.run
  
  persistence:
    enabled: true
    imageChartStorage:
      type: s3
      s3:
        region: eu-central-1
        bucket: registry
  
  jobservice:
    # The logger for jobs: "file", "database" or "stdout"
    jobLoggers:
      - database
  
  registry:
    # -- If true, the registry returns relative URLs in Location headers.
    # -- Enable it if Harbor is behind the reverse proxy like ingress-Nginx or Traefik. Doesn't require it for AWS LB Controller.
    # -- https://github.com/goharbor/harbor-helm/issues/345
    relativeurls: true
  
  chartmuseum:
    enabled: false
  
  notary:
    enabled: false
  
  database:
    type: external
    external:
      host: "postgres.local.naim.run"
      port: "5432"
      username: "harbor"
      sslmode: "require"
  
  metrics:
    enabled: true
    serviceMonitor:
      enabled: true
      additionalLabels:
        release: kube-prometheus