apiVersion: apps/v1
kind: Deployment
metadata:
  name: cloudflared
#  namespace: cloudflared
  labels:
    app: cloudflared
spec:
  replicas: 2
  selector:
    matchLabels:
      app: cloudflared
  template:
    metadata:
      labels:
        app: cloudflared
    spec:
      containers:
        - name: cloudflared
          image: cloudflare/cloudflared:2024.4.1
          args:
            - tunnel
            - '--no-autoupdate'
            - run
            - '--token'
            - $(token)
          envFrom:
            - secretRef:
                name: cloudflared-token
          imagePullPolicy: IfNotPresent
          securityContext:
            readOnlyRootFilesystem: true
      restartPolicy: Always