apiVersion: apps/v1
kind: Deployment
metadata:
  name: cloudflared
#  namespace: cloudflared
  labels:
    app: cloudflared
spec:
  replicas: 2
  selector:
    matchLabels:
      app: cloudflared
  template:
    metadata:
      labels:
        app: cloudflared
    spec:
      containers:
        - name: cloudflared
          image: cloudflare/cloudflared:2024.4.1
          args:
            - tunnel
            - '--no-autoupdate'
            - run
            - '--token'
            - $(token)
          livenessProbe:
            httpGet:
              # Cloudflared has a /ready endpoint which returns 200 if and only if
              # it has an active connection to the edge.
              path: /ready
              port: 2000
            failureThreshold: 1
            initialDelaySeconds: 10
            periodSeconds: 10
          envFrom:
            - secretRef:
                name: cloudflared-token
          imagePullPolicy: IfNotPresent
          securityContext:
            readOnlyRootFilesystem: true
      restartPolicy: Always