apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "debug-kubernetes-secrets.fullname" . }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: {{ include "debug-kubernetes-secrets.name" . }}
  template:
    metadata:
      labels:
        app: {{ include "debug-kubernetes-secrets.name" . }}
    spec:
      containers:
        - name: "{{ .Values.container.name }}"
          image: "{{ .Values.container.image.repository }}:{{ .Values.container.image.tag }}"
          imagePullPolicy: {{ .Values.container.image.pullPolicy }}
          command: ["sh", "-c", "cat /mnt/secrets/password && sleep 3600"]
          volumeMounts:
            - name: secret-volume
              mountPath: /mnt/secrets
      volumes:
        - name: secret-volume
          secret:
            secretName: {{ .Values.secret.name }}
