apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.secret.name }}
type: Opaque
data:
  username: {{ .Values.secret.data.username | b64enc }}
  password: {{ .Values.secret.data.password | b64enc }}
