apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: argo-workflows-components-appset
  namespace: argo
  labels:
    name: workflows
spec:
  generators:
    - matrix:
        generators:
          - git:
              repoURL: https://github.com/tankibaj/gitops-scratch-paper.git
              revision: development
              directories:
                - path: 'argo-workflows-components/*'
          - list:
              elements:
                - cluster: management
                  url: https://kubernetes.default.svc
#                - cluster: development
#                  url: https://development.local.naim.run
  template:
    metadata:
      name: '{{path.basename}}-{{cluster}}'
      labels:
        name: workflows
    spec:
      project: gitops
      source:
        repoURL: https://github.com/tankibaj/gitops-scratch-paper.git
        targetRevision: development
        path: '{{path}}/{{cluster}}'
      destination:
        server: '{{url}}'
        namespace: argo
      syncPolicy:
        syncOptions:
          - CreateNamespace=true