fullnameOverride: "postgres"
auth:
  enablePostgresUser: true
  username: "demouser"
  database: "demodb"
  existingSecret: "postgres-secret"
  secretKeys:
    adminPasswordKey: "adminPassword"
    userPasswordKey: "userPassword"