apiVersion: external-secrets.io/v1beta1
kind: ClusterSecretStore
metadata:
  name: vault-management
spec:
  provider:
    vault:
      server: https://vault.local.naim.run # "http://vault.vault.svc.cluster.local:8200" # Calling local vault running in same cluster
      path: "management"
      version: "v2"
      auth:
        # VaultAppRole authenticates with Vault using the
        # App Role auth mechanism
        # https://www.vaultproject.io/docs/auth/approle
        appRole:
          path: "approle" # -- Path where the App Role authentication backend is mounted
          roleId: "ca595750-615e-be7b-ee3d-1772ce5832a0" # -- RoleID configured in the App Role authentication backend
          # Reference to a key in a K8 Secret that contains the App Role SecretId
          secretRef:
            name: "vault-secret"
            key: "secret-id"
            namespace: external-secrets # -- namespace where you can find the secret id for given app role