# Define API version and resource type for ClusterSecretStore
apiVersion: external-secrets.io/v1beta1
kind: ClusterSecretStore
metadata:
  name: vault-management
  namespace: external-secrets
spec:
  # Indicate that the secret store is a Vault
  provider:
    vault:
      # URL of the Vault server
      server: https://vault.local.naim.run
      
      # Vault path where secrets are stored
      path: "platform-engineers"

      # Vault API version to use
      version: "v2"

      # Authentication details for the Vault server
      auth:
        # Using Vault's AppRole authentication method
        appRole:
          # Path where AppRole authentication is enabled in Vault
          path: "approle"

          # RoleID for this specific AppRole in Vault
          roleId: "ca595750-615e-be7b-ee3d-1772ce5832a0"

          # Reference to a Kubernetes Secret containing the SecretID for this AppRole
          secretRef:
            # Secret name containing the SecretID
            # To create this secret, use: 
            # kubectl create secret generic vault-approle-secret \
            # --namespace=external-secrets \
            # --from-literal=token='your-secret-id-here'
            name: "vault-approle-secret"

            # Key within the Secret where the SecretID is stored
            key: "token"

            # Namespace where the Secret resides
            namespace: external-secrets
