apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: vault-external-secret
  namespace: default
spec:
  refreshInterval: "15s"
  secretStoreRef:
    name: vault-management          # -- Name of ClusterSecretStore/SecretStore
    kind: ClusterSecretStore
  target:
    name: test-secret-from-vault    # -- Kubernetes secret object name
  data:
    - secretKey: password           # -- This will be the key in kubernetes secret.
      remoteRef:                    # -- Vault information about secret
        key: management/foo         # -- Path of vault secret
        property: password          # -- Key of secret in vault
    - secretKey: user
      remoteRef:
        key: management/foo
        property: user