apiVersion: argoproj.io/v1alpha1
kind: Sensor
metadata:
  name: sensor-buildkit
spec:
  template:
    serviceAccountName: operate-workflow-sa # buildkit-sa
  dependencies:
    - name: build-event
      eventSourceName: eventsource-webhook
      eventName: playground-gitea
  triggers:
    - template:
        name: workflow-trigger
        argoWorkflow:
          operation: submit # This is the key addition
          source:
            resource:
              apiVersion: argoproj.io/v1alpha1
              kind: Workflow
              metadata:
                generateName: buildkit-
              spec:
                serviceAccountName: operate-workflow-sa
                arguments:
                  parameters:
                    - name: repo
                      value: ""  # Placeholder, will be replaced by the event data by parameter mapping below
                    - name: branch
                      value: ""  # Placeholder, will be replaced by the event data by parameter mapping below
                    - name: path
                      value: "."
                    - name: image
                      value: "thenaim/whalesay:latest"
                workflowTemplateRef:
                  name: buildkit
          parameters: # Explicitly define parameters to pass from the event to the workflow
            - src:
                dependencyName: build-event
                dataKey: body.repository.full_name
              dest: spec.arguments.parameters.0.value
            - src:
                dependencyName: build-event
                dataKey: body.ref
              dest: spec.arguments.parameters.1.value