apiVersion: argoproj.io/v1alpha1
kind: Sensor
metadata:
  name: sensor-workflow-payload
spec:
  template:
    serviceAccountName: operate-workflow-sa
  dependencies:
    - name: test-dep
      eventSourceName: eventsource-webhook
      eventName: playground-gitea
  triggers:
    - template:
        name: webhook-workflow-trigger
        k8s:
          operation: create
          source:
            resource:
              apiVersion: argoproj.io/v1alpha1
              kind: Workflow
              metadata:
                generateName: webhook-
              spec:
                serviceAccountName: operate-workflow-sa
                entrypoint: whalesay
                arguments:
                  parameters:
                    - name: webhook-payload
                      value: "{{toJson .}}"  # Capture the entire event payload
                templates:
                  - name: whalesay
                    inputs:
                      parameters:
                        - name: webhook-payload
                    container:
                      image: busybox
                      command: ["sh", "-c"]
                      args: ["echo 'Payload: {{inputs.parameters.webhook-payload}}'"]