apiVersion: argoproj.io/v1alpha1
kind: Sensor
metadata:
  name: sensor-workflow-payload
spec:
  template:
    serviceAccountName: operate-workflow-sa
  dependencies:
    - name: test-dep
      eventSourceName: eventsource-webhook
      eventName: playground-gitea
  triggers:
    - template:
        name: webhook-workflow-trigger
        k8s:
          group: argoproj.io
          version: v1alpha1
          resource: workflows
          operation: create
          source:
            resource:
              apiVersion: argoproj.io/v1alpha1
              kind: Workflow
              metadata:
                generateName: webhook-
              spec:
                serviceAccountName: operate-workflow-sa
                entrypoint: whalesay
                arguments:
                  parameters:
                    - name: repo
                      value: ""  # Placeholder, will be replaced by the event data by parameter mapping below
                    - name: branch
                      value: ""  # Placeholder, will be replaced by the event data by parameter mapping below
                    - name: path
                      value: "."
                    - name: image
                      value: "thenaim/whalesay:latest"
                templates:
                  - name: whalesay
                    inputs:
                      parameters:
                        - name: repo
                        - name: branch
                    container:
                      image: docker/whalesay
                      command: [ "cowsay" ]
                      args: [ "Repo: {{inputs.parameters.repo}}, Branch: {{inputs.parameters.branch}}, Path: {{inputs.parameters.path}}, Image: {{inputs.parameters.image}}" ]
          parameters: # Explicitly define parameters to pass from the event to the workflow
            - src:
                dependencyName: test-dep
                dataKey: body.repository.full_name
              dest: spec.arguments.parameters.0.value
            - src:
                dependencyName: test-dep
                dataKey: body.ref
              dest: spec.arguments.parameters.1.value