apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: prometheus-crds-appset
  namespace: argocd
  labels:
    name: observability
spec:
  generators:
    - list:
        elements:
          - cluster: in-cluster
            url: https://kubernetes.default.svc
            values:
              tag: production
#          - cluster: development
#            url: https://dev-cluster.local.naim.run
#            values:
#              tag: production
  template:
    metadata:
      name: 'prometheus-crds-{{cluster}}'
      labels:
        name: observability
    spec:
      project: gitops
      source:
        repoURL: https://github.com/tankibaj/gitops-scratch-paper.git
        targetRevision: main
        path: prometheus-crds/{{values.tag}}
      destination:
        server: '{{url}}'
        namespace: prometheus-agent
      syncPolicy:
        syncOptions:
          - Replace=true # https://github.com/prometheus-operator/prometheus-operator/issues/4439#issuecomment-1110279191
          - CreateNamespace=true