apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: velero-appset
  namespace: argocd
  labels:
    name: velero
spec:
  generators:
    - list:
        elements:
          - cluster: management
            url: https://kubernetes.default.svc
            values:
              tag: main
#          - cluster: development
#            url: https://development-cluster.local.naim.run
#            values:
#              tag: development
  template:
    metadata:
      name: 'velero-{{cluster}}'
      labels:
        name: velero
    spec:
      project: gitops
      source:
        repoURL: https://github.com/tankibaj/gitops-scratch-paper.git
        targetRevision: development
        path: velero/{{values.tag}}
        helm:
          releaseName: velero
          valueFiles:
            - values.yaml
          parameters:
            - name: velero.configuration.backupStorageLocation.prefix
              value: '{{cluster}}'
      destination:
        server: '{{url}}'
        namespace: velero
      syncPolicy:
        syncOptions:
          - CreateNamespace=true