apiVersion: argoproj.io/v1alpha1
kind: WorkflowTemplate
metadata:
  name: drug-info
spec:
  entrypoint: main
  # We use a volume claim template so that we can have a shared workspace.
  volumeClaimTemplates:
    - metadata:
        name: workspace
      spec:
        accessModes: [ "ReadWriteOnce" ]
        resources:
          requests:
            storage: 100Mi
  templates:
    - name: main
      dag:
        tasks:
          - name: clone
            template: clone
          - name: debug-info
            template: debug-info
            depends: "clone"

    # -- Git Checkout --
    - name: clone
      container:
        volumeMounts:
          - mountPath: /workspace
            name: workspace
        image: alpine/git:v2.43.0
        workingDir: /workspace
        command: [ sh, -c ]
        args:
          - |
            branch_name=$(echo '{{workflow.parameters.branch}}' | awk -F'/' '{print $3}')
            git clone --branch $branch_name '{{workflow.parameters.repo_url}}' .

    # -- Debug --
    - name: debug-info
      container:
        volumeMounts:
          - mountPath: "{{workflow.parameters.work_dir}}"
            name: workspace
        workingDir: "{{workflow.parameters.work_dir}}"
        image: alpine:latest
        command: [ sh, -c ]
        args:
          - |
            id
            echo "Listing /work directory:"
            ls -lah "{{workflow.parameters.work_dir}}"