# SUMMARY:
#
# This workflow demonstrates a Terraform plan and apply process using Argo Workflows.
#
# DESCRIPTION:
#
# The workflow has four stages:
#
# * Cloning the Git repository containing Terraform configuration
# * Running 'terraform plan' to create an execution plan
# * A manual approval step
# * Running 'terraform apply' to apply the changes
#
# USAGE:
#
# Requires setting up secrets for accessing the Terraform backend and any other sensitive information.
#
apiVersion: argoproj.io/v1alpha1
kind: WorkflowTemplate
metadata:
  name: terra-ai
spec:
  # must complete in 8h (28,800 seconds)
  activeDeadlineSeconds: 28800
  ttlStrategy:
    # keep workflows for 1d (86,400 seconds)
    secondsAfterCompletion: 28800 # Time to live after the workflow is completed, replaces ttlSecondsAfterFinished
  #    secondsAfterSuccess: 20 # Time to live after workflow is successful
  #    secondsAfterFailure: 120 # Time to live after workflow fails
  entrypoint: main
  volumeClaimTemplates:
    - metadata:
        name: terraform-workspace
      spec:
        accessModes: ["ReadWriteOnce"]
        resources:
          requests:
            storage: 1Gi
  templates:
    - name: main
      dag:
        tasks:
          - name: checkout-repo
            template: checkout-repo
            arguments:
              parameters:
                - name: git_repo_url
                  value: "{{workflow.parameters.git_repo_url}}"
                - name: git_branch_name
                  value: "{{workflow.parameters.git_branch_name}}"
          - name: terraform-plan
            template: plan
            depends: "checkout-repo"
            arguments:
              parameters:
                - name: terraform_config_dir
                  value: "{{workflow.parameters.terraform_config_dir}}"
          - name: manual-approve
            template: approve
            depends: "terraform-plan"
          - name: terraform-apply
            template: apply
            depends: "manual-approve"
            arguments:
              parameters:
                - name: terraform_config_dir
                  value: "{{workflow.parameters.terraform_config_dir}}"

    # -- Git Checkout --
    - name: checkout-repo
      inputs:
        parameters:
          - name: git_repo_url
          - name: git_branch_name
      container:
        volumeMounts:
          - mountPath: /workspace
            name: terraform-workspace
        image: alpine/git:v2.43.0
        workingDir: /workspace
        command: [sh, -c]
        args:
          - |
            git clone --branch '{{inputs.parameters.git_branch_name}}' '{{inputs.parameters.git_repo_url}}' .

    # -- Terraform Plan --
    - name: plan
      inputs:
        parameters:
          - name: terraform_config_dir
      container:
        volumeMounts:
          - mountPath: /workspace
            name: terraform-workspace
        image: hashicorp/terraform:1.7.2
        workingDir: /workspace
        command: [sh, -c]
        args:
          - |
            echo "{{inputs.parameters.terraform_config_dir}}"
            terraform -chdir="{{inputs.parameters.terraform_config_dir}}" init -upgrade
            terraform -chdir="{{inputs.parameters.terraform_config_dir}}" plan -out=tfplan -input=false

    # -- Manual Approval --
    - name: approve
      suspend: {}

    # -- Terraform Apply --
    - name: apply
      inputs:
        parameters:
          - name: terraform_config_dir
      container:
        volumeMounts:
          - mountPath: /workspace
            name: terraform-workspace
        image: hashicorp/terraform:1.7.2
        workingDir: /workspace
        command: [sh, -c]
        args:
          - |
            terraform -chdir="{{inputs.parameters.terraform_config_dir}}" apply -auto-approve "tfplan"
            terraform -chdir="{{inputs.parameters.terraform_config_dir}}" output