velero:
  initContainers:
    - name: velero-plugin-for-aws
      image: velero/velero-plugin-for-aws:v1.8.2
      imagePullPolicy: Always
      volumeMounts:
        - mountPath: /target
          name: plugins

  metrics:
    enabled: true
    serviceMonitor:
      enabled: true
      additionalLabels:
        release: kube-prometheus

  configuration:
    backupStorageLocation:
      - name:
        provider: aws
        bucket: velero-backup-bucket
        config:
          region: eu-central-1

  credentials:
    useSecret: false

  snapshotsEnabled: false

  schedules:
    daily-backup:
      disabled: false
      schedule: "0 01 * * *" # -- Daily at 1AM
      useOwnerReferencesInBackup: false
      template:
        ttl: "720h" # -- Backup retention period
        includedNamespaces:
          - gitea