apiVersion: argoproj.io/v1alpha1
kind: EventSource
metadata:
  name: gitea-webhook
  namespace: argo-events-workflow
spec:
  service:
    ports:
      - port: 12000 # Port where the service will listen to
        targetPort: 12000
  webhook:
    gitea-push-event:
      endpoint: /push
      port: "12000"
      method: POST

---
# Write an ingress manifest for the event source
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: gitea-webhook
  namespace: argo-events-workflow
spec:
  ingressClassName: public
  rules:
    - host: gitea-webhook.local.naim.run
      http:
        paths:
          - backend:
              service:
                name: gitea-webhook
                port:
                  number: 12000
            path: / #/gitea-webhook(/|$)(.*)
            pathType: Prefix