apiVersion: k8s.keycloak.org/v2alpha1
kind: Keycloak
metadata:
  name: keycloak-instance
  namespace: keycloak
spec:
  instances: 1
  db:
    vendor: postgres
    usernameSecret:
      name: keycloak-db-secret
      key: username
    passwordSecret:
      name: keycloak-db-secret
      key: password
    host: postgres.postgres.svc.cluster.local
  http:
    httpEnabled: false
  hostname:
#    hostname: identity.local.naim.run
#    admin: identity-admin.local.naim.run
    strict: false
    strictBackchannel: false
  ingress:
    enabled: false
  proxy:
    headers: forwarded
  additionalOptions:
    - name: hostname-url
      value: "https://identity.local.naim.run"
    - name: hostname-admin-url
      value: "https://identity.local.naim.run"
#    - name: proxy
#      value: "edge"
    - name: log-console-color
      value: "true"
    - name: log-level
      value: "INFO"