velero:
  initContainers:
    - name: velero-plugin-for-aws
      image: velero/velero-plugin-for-aws:v1.4.1
      imagePullPolicy: Always
      volumeMounts:
        - mountPath: /target
          name: plugins
  
  metrics:
    enabled: true
    serviceMonitor:
      enabled: true
      additionalLabels:
        release: kube-prometheus
  
  configuration:
    provider: aws
    backupStorageLocation:
      # -- Amazon S3 bucket name
      bucket: velero-backups
      # -- Amazon S3 bucket path/directory
      # prefix: velero
      config:
        region: eu-central-1
    volumeSnapshotLocation:
      name: aws
      config:
        region: us-east-1
    # -- Set true for backup all pod volumes without having to apply annotation on the pod when used restic Default: false. Other option: false.
    defaultVolumesToRestic: true
  
  credentials:
    useSecret: false
  
  # Whether to create backupstoragelocation crd, if false => do not create a default backup location
  backupsEnabled: true
  
  # -- Whether to create volumesnapshotlocation crd, if false => disable snapshot feature
  snapshotsEnabled: false
  
  # -- Whether to deploy the restic daemonset.
  deployRestic: true
  
  restic:
    podSecurityContext:
      runAsUser: 999
  
  # -- Backup schedules to create.
  schedules:
    daily-backup:
      disabled: false
      # -- Daily at 1AM
      schedule: "0 01 * * *"
      # -- Specifies whether to use OwnerReferences on backups created by this Schedule. Notice: if set to true, when schedule is deleted, backups will be deleted too.
      useOwnerReferencesInBackup: false
      template:
        # -- Backup retention period
        ttl: "240h"
        # -- Namespaces to include in the backup (use '*' for all namespaces)
        includedNamespaces:
          - foo
