external-dns:
  fullnameOverride: external-dns

  serviceAccount:
    create: true
    annotations: {eks.amazonaws.com/role-arn: arn:aws:iam::XXXXXXXXXXXX:role/eks-development-irsa-external-dns}
    name: "external-dns"

  sources:
    - service
    - ingress

  policy: sync
  registry: txt
  txtOwnerId: "eks-development"
  domainFilters: [development.aws.naim.run]
  provider: aws