apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: promtail
  namespace: argocd
  labels:
    name: observability
spec:
  generators:
    - list:
        elements:
          - cluster: management
            url: https://kubernetes.default.svc
            endpoint: http://loki-gateway.loki.svc.cluster.local/loki/api/v1/push
            tenant_id: org1
          - cluster: development
            url: https://172.16.100.69:16443
            endpoint: https://logs.local.naim.run/loki/api/v1/push
            tenant_id: org1
  template:
    metadata:
      name: 'promtail-{{cluster}}'
      labels:
        name: observability
    spec:
      project: gitops
      sources:
        - repoURL: https://grafana.github.io/helm-charts
          chart: promtail
          targetRevision: 6.8.3
          helm:
            version: v3
            releaseName: promtail
            values: |
              promtail:
                config:
                  clients:
                    - url: '{{endpoint}}'
                      tenant_id: '{{tenant_id}}'
                      external_labels:
                        cluster: '{{cluster}}'
            valueFiles:
              - $values/components/promtail/values.yaml
        - ref: values
          repoURL: https://github.com/tankibaj/gitops-scratch-paper.git
          targetRevision: development
      destination:
        server: '{{url}}'
        namespace: promtail
      syncPolicy:
        syncOptions:
          - CreateNamespace=true