apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: prometheus-crds-appset
  namespace: argocd
  labels:
    name: observability
spec:
  generators:
    - list:
        elements:
          - cluster: management
            url: https://kubernetes.default.svc
            values:
              tag: main
          - cluster: development
            url: https://172.16.100.69:16443
            values:
              tag: main
  template:
    metadata:
      name: 'prometheus-crds-{{cluster}}'
      labels:
        name: observability
    spec:
      project: gitops
      source:
        repoURL: https://github.com/tankibaj/gitops-scratch-paper.git
        targetRevision: development
        path: prometheus/crds/{{values.tag}}
      destination:
        server: '{{url}}'
        namespace: prometheus
      syncPolicy:
        syncOptions:
          - Replace=true # https://github.com/prometheus-operator/prometheus-operator/issues/4439#issuecomment-1110279191
          - CreateNamespace=true