global:
  name: consul

server:
  storage: 2Gi # default: 10Gi

# -- Consul UI [Optional for debug]
ui:
  enabled: true
  ingress:
    enabled: true
    ingressClassName: public
    pathType: Prefix
    hosts:
      - host: consul.local.naim.run
        paths:
          - /