{{- if .Values.secrets.discord.create }}
apiVersion: v1
kind: Secret
metadata:
  name: discord-bot-secret
  labels:
    {{- include "discord-themoviedb-bot.labels" . | nindent 4 }}
type: Opaque
data:
  discord_bot_token: {{ .Values.secrets.discord.discord_bot_token | b64enc | quote }}
{{- end }}
---
{{- if .Values.secrets.themoviedb.create }}
apiVersion: v1
kind: Secret
metadata:
  name: themoviedb-secret
  labels:
    {{- include "discord-themoviedb-bot.labels" . | nindent 4 }}
type: Opaque
data:
  themoviedb_api_key: {{ .Values.secrets.themoviedb.themoviedb_api_key | b64enc | quote }}
{{- end }}
